### ISSUE TITLE
Project Ideas

### ISSUE THREAD

**Issue by jvivian** [jvivian/Children-of-Skynet#1]
[Santa Cruz ML Club Challenge](https://github.com/santacruzml/fall-17-scml-competition)

**Comment by jvivian** [comment]
@AaronJCooke @avacabro @nsjake — Here's where you can post

**Comment by jvivian** [comment]
Assignment Idea:

Each person builds a GAN to produce art in the style of a particular artist. The goal will then be to present 5 images, one of which is generated by the GAN, and have the others judge which is the real image and which is the generated image.

**Comment by nsjake** [comment]
Idea:

Celebrity tweet generator (originally mentioned during call)

Scrape Twitter for tweets of political leaders, celebrities, etc. Produce a network generates 140 character strings that are novel, but sound similar to real celebrities.

**Comment by avacabro** [comment]
Idea:

Predict bitcoin/e-coin from stock market or other relevant datasets

https://www.kaggle.com/mczielinski/bitcoin-historical-data

https://www.kaggle.com/aaron7sun/stocknews

**Comment by jvivian** [comment]
Hoppin on Jake's idea we could make a Trump bot, there's obviously enough source material lol.

**Comment by AaronJCooke** [comment]
I want to do something that will improve the world, not make it worse.

**Comment by jvivian** [comment]
Says the guy whose major is based around game theory ;)
